--- #YAML:1.0
name:                Formatter-HTML-Textile
version:             1.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::TokeParser:              0
    Test::More:                    0.47
    Test::Signature:               1.04
    Text::Textile:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
